# Generated by Django 4.2.2 on 2023-06-28 03:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=9)),
                ('certificado', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.carrera')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=7)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('penalidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.matricula')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.seccion'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('credito', models.IntegerField()),
                ('cupos', models.IntegerField()),
                ('horas', models.IntegerField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.seccion')),
            ],
        ),
        migrations.AddField(
            model_name='ciclo',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.semestre'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculaApp.departamento'),
        ),
    ]
