# Generated by Django 4.2.2 on 2023-06-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='fecha_nacimento',
            new_name='fecha_nacimiento',
        ),
    ]
