# Generated by Django 4.2.2 on 2023-07-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='certificado',
        ),
    ]
