# Generated by Django 4.2.2 on 2023-07-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculaApp', '0002_remove_estudiante_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
